@startuml

class Application {
    AccessCameraSystem()
    AccessNotificationSystem()
    AccessRegistrationSystem()
    AccessDatabase()
}
class NotificationSystem{
    NotifyUser()
    NotifyAuthorities()
}
class RegistrationSystem{
    EnterPersonalInfo()
    EnterUsername()
    EnterPassword()
    ValidatePassword()
    RegisterUser()
}
class LoginSystem {
EnterUsername()
EnterPassword()
}
class CameraSystem{
    DisplayVideo()
}
class AudioSystem {
    DisplayAudioWave()
}


Application -d-> NotificationSystem : Refers to
Application -> RegistrationSystem : Refers to
Application -> LoginSystem : Refers to
Application -l-> CameraSystem : Refers to
Application -u-> Database : Refers to
Application -d-> AudioSystem : Refers to


@endunml 
