@startuml

class Application {
    AccessLoginSystem()
    AccessRegistrationSystem()
}
class RegistrationSystem
{
    EnterPersonalInfo()
    EnterUsername()
    EnterPassword()
    ValidatePassword()
    RegisterUser()

}
class LoginSystem {
EnterUsername()
EnterPassword()
}

class Database{
StoreUser()
CheckUser()
CheckPass()
}



LoginSystem -d-> Database : Sign in user
RegistrationSystem -d-> Database : Store data
Database -> Application : Authorize access
Application -> RegistrationSystem : Register request
Application -> LoginSystem : Login request
User -u-> Application : Input
Application -d-> User : Output

@enduml