@startuml

title Login System State Diagram
[*] --> LoginSystem
LoginSystem :EnterUsername()\nEnterPassword()
False:Password Incorrect
True:Password Correct
Evaluation:Checking Database


LoginSystem -> Evaluation:CheckUser()
Evaluation --> True : CheckPassword()
Evaluation --> False:CheckPassword()
LoginSystem <-- False : AccessLoginSystem()
RegistrationSytem <- False :AccessRegistrationSystem()
False --> [*]:ExitApp()
note left
Exit System 
end note
True -> Application:AccessApp()

@enduml