@startuml

title Notification System State Diagram

start

:NotificationFeed;
if(Detected Emergency?) then (Yes)
    :SendAlert();
    :ContactParents(PhoneNumber);
    :ContactAuthority(Local_Authority_Num);
else (No)
    :UpdateFeed();
endif
stop    
note left 
MainMenu() 
end note
@enduml