@startuml

title Registration System State Diagram
[*] --> PersonalInformation: Register()
PersonalInformation --> Username
Username --> Password
Username: Enter Username
Password: Enter Password
Password -> Confirmation
Confirmation --> LoginSystem : Registration Succesful
Confirmation --> False
Confirmation:Enter Password Again
Password <-- False : Retry
False --> [*]
note left
Exit System 
end note
LoginSystem: Go To Login
PersonalInformation:Enter Email\nEnter Phone Number

@enduml