@startuml

title Registration System State Diagram
[*] --> PersonalInformation: EnterPersonalInfo()
PersonalInformation --> Username:EnterUsername()
Username --> Password:EnterPassword()
Username: Enter Username
Password: Enter Password
Password -> Validation:EnterPassword()
Validation --> True : ValidatePassword()
Validation --> False:ValidatePassword()
True --> LoginSystem : RegisterUser()
Validation:Enter Password Again
Password <-- False : EnterPassword()
False --> [*]:ExitSystem()
note left
Exit System 
end note
LoginSystem: Go To Login
PersonalInformation:Enter Email\nEnter Phone Number

@enduml